---
- name: "Provision Vagrant"
  hosts: default
  sudo: yes
  remote_user: vagrant
  roles:
    - common
    - repo_install
    - php7
    - mysql
    - apache
    - composer
    - bash
    - java
    - elasticsearch
    - kibana
